repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.1
    hooks:
      - id: check-github-workflow
