name: Build LaTeX document with make

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        shell: bash
        run: |
          make install
          make compile

      - name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: draft_make         # The branch the action should deploy to.
          folder: publish            # The folder the action should deploy.