name: Build LaTeX document

on: 
  [push]

jobs:    
  build_paper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - uses: cvxgrp/.github/actions/latex@main
        with:
          paper: '*.tex'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      #- uses: cvxgrp/.github/actions/latex@main
      #  with:
      #    paper: Hydra.tex
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
