name: Build LaTeX document
on: [push]

jobs:    
  build_paper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
          
      - name: Compile Original
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Hydra.tex
      
      - name: Compile Fourier
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Fourier.tex
          
      - name: Upload Original
        uses: actions/upload-artifact@v3
        with:
          name: Paper
          path: Hydra.pdf

      - name: Upload Fourier
        uses: actions/upload-artifact@v3
        with:
          name: Paper
          path: Fourier.pdf
