name: Build LaTeX document with make

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        shell: bash
        run: |
          make install
          make compile

      - name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          # The branch the action should deploy to.
          branch: draft_make
          # The folder the action should deploy.
          folder: publish
